import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], display: 'swap' });


// import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

// const outfit  = Outfit({
//   subsets: ["latin"], weight: ["400", "500", "600", "700"],
// });
// const ovo  = Ovo({
//   subsets: ["latin"], weight: ["400"],
// });

export const metadata = {
  title: "Mohammed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
       className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
// dark:bg-[#11001f] dark:text-white